### PR TITLE
Switch to new csproj and v7

### PR DESCRIPTION
**Pull request by danielmarbach**
I started migrating to the new csproj format and NSB v7. Currently I still have larger issues with the nuget dependencies in the example application. I get a lot of NU1605 errors when building. Will investigate

### CODE REVIEW

**Comment by buvinghausen** [comment]
From the looks of it this repository is orphaned/abandoned.

**Comment by tekmaven** [comment]
Hey @buvinghausen - it's not!  Just have been occupied with other high priority work.  I will circle around to this soon!

**Comment by buvinghausen** [comment]
@tekmaven do you have a timeline or ETA? We need to implement Sagas and Databus soon and would like to do so via Mongo rather than SQL but we're running on .NET Core on Linux so support for v7 is a must...

**Comment by tekmaven** [comment]
@buvinghausen  I have reviewed the PR.  This is a great work-in-progress and does not build for me locally in VS2017.  As @danielmarbach  stated in the original PR: "I get a lot of NU1605 errors when building. Will investigate".  NSB 7 is not released yet.  I will continue to work on it over the coming weeks.

@danielmarbach - thank you for the great head start here.

**Comment by danielmarbach** [comment]
I can update this PR next week -------- Originalnachricht --------Betreff: Re: [tekmaven/NServiceBus.Persistence.MongoDb] Switch to new csproj and v7 (#24)Von: Ryan Hoffman An: "tekmaven/NServiceBus.Persistence.MongoDb" Cc: Daniel Marbach ,Mention @buvinghausen  I have reviewed the PR.  This is a great work-in-progress and does not build for me locally in VS2017.  As @danielmarbach  stated in the original PR: "I get a lot of NU1605 errors when building. Will investigate".  NSB 7 is not released yet.  I will continue to work on it over the coming weeks.
@danielmarbach - thank you for the great head start here.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tekmaven/NServiceBus.Persistence.MongoDb","title":"tekmaven/NServiceBus.Persistence.MongoDb","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tekmaven/NServiceBus.Persistence.MongoDb"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tekmaven in #24: @buvinghausen  I have reviewed the PR.  This is a great work-in-progress and does not build for me locally in VS2017.  As @danielmarbach  stated in the original PR: \"I get a lot of NU1605 errors when building. Will investigate\".  NSB 7 is not released yet.  I will continue to work on it over the coming weeks.\r\n\r\n@danielmarbach - thank you for the great head start here.\r\n\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/pull/24#issuecomment-350520743"}}}

**Comment by pedershk** [comment]
Hi. Nothing has happened with this PR over the past 6 months. We're looking to avoid the SQL saga persister, and was hoping this would be ready for NSB7 by now. Any progress updates? :)

**Comment by CyAScott** [comment]
I created another [PR ](https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/pull/25) that does port the solution to .net standard 2 with NSB v7 support. All test pass and the example project runs.

**Comment by tekmaven** [comment]
Thank you!  This looks awesome!  We will review and merge this in.

**Comment by timbussmann** [comment]
I'm going to close this issue as this repository is no longer actively maintained. The [officially supported](https://github.com/Particular/NServiceBus.Storage.MongoDB) MongoDB persistence package supports version 7 of NServiceBus and the new csproj format 🎉

**Pull request closed without merging**
